[project]
name = "eric-monitors-watchdog"
version = "0.0.3"
description = ""
authors = [
    {name = "Luca Stretti",email = "laxertu@gmail.com"}
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "watchdog (>=6.0.0,<7.0.0)",
    "eric-sse (>=2.1.1.2,<3.0.0.0)"
]
