[project]
name = "eric-monitors-python-logger"
version = "0.0.1"
description = ""
authors = [
    {name = "Luca Stretti",email = "laxertu@gmail.com"}
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.10"
